### ISSUE TITLE
U_regulizer inconsistent with the paper

### ISSUE THREAD

**Issue by AwesomeLemon** [longxianlei/G-ResNeXt_GroupNet#1]
Hi.
First of all, thank you so much for actually implementing the whole pipeline of the paper (something the original authors didn't bother with).

As to my actual concern: in your code you use the same formula for regularization as in the authors' code (``U_regularizer = 2**(self.K + torch.sum(self.gate))``). However, it is not equivalent to the formula from the paper (Equation 9). Could you tell me whether you've maybe experimented with the proper formula and it didn't work out, or have you just used the formula from the authors' code without worrying about it?

**Comment by longxianlei** [comment]
Hi, AwesomeLemon.
I am sorry for not replying this issue in time.
I have reviewed the original paper twice and rechecked the code:
 `(U_regularizer = 2**(self.K + torch.sum(self.gate)))`.
As the **Equation 9** described, `L=sum(L_k）= sum(C^(l) \prod_{k=0}^(K^l) (1+g_(k)^l)`.
Now, we only consider 1 layer. For instance, the input C_in and output channel C_out is 8. So, the maximum computation cost is 8x8=64. At this time, k=3, g_k=1 (g_1=g_2=g_3=1).
The minimum is 8, at this time, k=3, g_k=0 (g_1=g_2=g_3=0).
So, U_regularizer = 2**(self.K + sum(self.gate)). In this example, K is 3, and sum(self.gate) is 3(maximum) or 0(minimum). So, the U_regularizer is 2**(3+3)=64 or 2**(3+0)=8.
Actually, these two equations can finally get the same results.
Remember, self.K=log_2(C)=log2(8)=3.
The total cost is sum up every layers' U_regularizer .
Hope you understand this process. Feel free to comment on this issue if you have any confusion.

**Comment by AwesomeLemon** [comment]
Ah, so I was too quick to judge, shame on me.
Yes, now I understand the process, thank you.
